<template>
  <div class="container">
    <h1>Verify Account</h1>
    <p>{{ introMessage }}</p>
    <div v-if="errors.length" class="alert alert-warning">
      <ul>
        <li v-for="e in errors" :key="e">{{ e }}</li>
      </ul>
    </div>
    <form @submit.prevent="onSubmit">
      <div class="mb-3">
        <label class="form-label">Verification Code</label>
        <input v-model="code" class="form-control" required />
      </div>
      <button type="submit" class="btn btn-primary" :disabled="!code">
        Verify
      </button>
    </form>
    <button
      class="btn btn-link mt-3"
      @click="onSendNewCode"
      :disabled="resendDisabled"
    >
      Send New Code
      <span v-if="resendDisabled"> in {{ countdown }}s</span>
    </button>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import AuthService, { MfaMethod } from "@/services/AuthService";

export default defineComponent({
  name: "VerifyAccountView",
  data() {
    return {
      code: "",
      errors: [] as string[],
      introMessage: "",
      resendDisabled: false,
      countdown: 0,
      resendCooldownSeconds: 30,
      MfaMethod,
    };
  },
  created() {
    this.startResendCooldown(this.resendCooldownSeconds);
    if (this.$route.path.includes("mfa-email")) {
      this.introMessage =
        "Enter the verification code that was sent to your email inbox.";
    } else if (this.$route.path.includes("mfa-sms")) {
      this.introMessage =
        "Enter the verification code that was sent to your phone.";
    } else if (this.$route.path.includes("mfa-otp")) {
      this.introMessage =
        "Enter the one-time password generated by your authenticator app.";
    } else {
      this.introMessage =
        "Enter the verification code that was sent to your email.";
    }
  },
  methods: {
    async onSubmit() {
      try {
        if (this.$route.path.includes("mfa-otp")) {
          const username = localStorage.getItem("verifyUsername") || "";
          await AuthService.verifyAuthenticator(username, this.code);
          this.$router.push("/");
        } else if (this.$route.path.includes("mfa-")) {
          await AuthService.verifyAccount(this.code, true);
          this.$router.push("/");
        } else {
          await AuthService.verifyAccount(this.code, false);
          alert("Account verified.");
          this.$router.push("/login");
        }
      } catch (e: any) {
        this.errors = ["Invalid verification code"];
      }
    },
    async onSendNewCode() {
      const username = localStorage.getItem("verifyUsername") || "";
      const method = this.$route.path.includes("mfa-email")
        ? MfaMethod.Email
        : MfaMethod.Sms;
      try {
        await AuthService.sendNewVerificationCode(username, method);
        this.startResendCooldown();
      } catch (err: any) {
        if (err.response?.data?.remainingSeconds) {
          this.startResendCooldown(err.response.data.remainingSeconds);
        } else {
          this.errors = [
            err.response?.data?.message || "Error sending new code.",
          ];
        }
      }
    },
    startResendCooldown(seconds?: number) {
      this.resendDisabled = true;
      this.countdown = seconds ?? this.resendCooldownSeconds;
      const interval = setInterval(() => {
        this.countdown--;
        if (this.countdown <= 0) {
          this.resendDisabled = false;
          clearInterval(interval);
        }
      }, 1000);
    },
  },
});
</script>
