import { Component, Inject, OnInit } from '@angular/core';
import { AuthService } from '../../core/_services/auth.service';
import { Router } from '@angular/router';
import { LoggerService } from '../../core/_services/logger.service';
import { AppConfig, VerifyTotpModel } from '../../_api';
import { APP_CONFIG } from '../../core/_services/config-injection';

@Component({
  selector: 'app-verify-account',
  templateUrl: './verify-account.component.html',
  styleUrl: './verify-account.component.scss',
})
export class VerifyAccountComponent implements OnInit {
  verificationCode: string = '';
  errors: string[] = [];
  introMessage: string;

  constructor(
    @Inject(APP_CONFIG) public config: AppConfig,
    private authService: AuthService,
    private logger: LoggerService,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.introMessage = location.href.includes('email')
      ? 'Enter the verification code that was sent to your email inbox'
      : 'Enter the verification code that was sent to your phone';

    if (location.href.includes('otp'))
      this.introMessage =
        'Enter the one-time password generated by your authenticator app.';
  }

  canSubmit(): boolean {
    return !!this.verificationCode;
  }

  onSubmit(): void {
    if (location.href.includes('otp')) {
      this.processOtp();
      return;
    }

    this.authService.verifyAccount(this.verificationCode).subscribe({
      next: (data) => {
        if (location.href.includes('mfa')) {
          setTimeout(
            () => (window.location.href = this.config.environment.url),
            1000
          );
        } else {
          this.logger.success('Account successfully verified.');
          this.router.navigateByUrl('/account/login');
        }
      },
      error: (error) => {
        this.errors = ['Invalid verification code'];
      },
    });
  }

  private processOtp() {
    const username = localStorage.getItem('verifyUsername');
    if (username != null) {
      this.authService
        .verifyAuthenticator(username, this.verificationCode)
        .subscribe({
          next: (data: any) => {
            debugger;
            this.logger.success('MFA verification successful.');
            this.authService.handleJwtResponse(data);
            setTimeout(
              () => (window.location.href = this.config.environment.url),
              1000
            );
          },
          error: () => {
            this.errors = ['Invalid OTP verification code'];
          },
        });
    }
  }
}
