import { Component, Inject, OnInit } from '@angular/core';
import { AuthService } from '../../core/_services/auth.service';
import { Router } from '@angular/router';
import { LoggerService } from '../../core/_services/logger.service';
import { AppConfig, MfaMethod, SimpleAuthSettings } from '../../_api';
import { APP_CONFIG } from '../../core/_services/config-injection';

@Component({
  selector: 'app-verify-account',
  templateUrl: './verify-account.component.html',
  styleUrl: './verify-account.component.scss',
})
export class VerifyAccountComponent implements OnInit {
  verificationCode: string = '';
  errors: string[] = [];
  introMessage: string;
  resendDisabled: boolean = false;
  countdown: number = 0;
  resendCooldownSeconds: number;
  simpleAuthSettings: SimpleAuthSettings;

  constructor(
    @Inject(APP_CONFIG) public appConfig: AppConfig,
    private authService: AuthService,
    private logger: LoggerService,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.resendCooldownSeconds = this.simpleAuthSettings.resendCodeDelaySeconds;
    this.startResendCooldown(this.simpleAuthSettings.resendCodeDelaySeconds);

    this.introMessage = location.href.includes('email')
      ? 'Enter the verification code that was sent to your email inbox'
      : 'Enter the verification code that was sent to your phone';

    if (location.href.includes('otp'))
      this.introMessage =
        'Enter the one-time password generated by your authenticator app.';
  }

  canSubmit(): boolean {
    return !!this.verificationCode;
  }

  onSubmit(): void {
    if (location.href.includes('otp')) {
      this.processOtp();
      return;
    }

    this.authService.verifyAccount(this.verificationCode).subscribe({
      next: (data) => {
        if (location.href.includes('mfa')) {
          setTimeout(
            () =>
              (window.location.href = this.simpleAuthSettings.environment.url),
            1000
          );
        } else {
          this.logger.success('Account successfully verified.');
          this.router.navigateByUrl('/account/login');
        }
      },
      error: (error) => {
        this.errors = ['Invalid verification code'];
      },
    });
  }

  onSendNewCode(): void {
    const username = localStorage.getItem('verifyUsername');
    const mfaMethod = location.href.includes('email')
      ? MfaMethod.Email
      : MfaMethod.Sms;

    if (!username) {
      this.errors = ['Unable to determine username. Please try again.'];
      return;
    }

    this.authService.sendNewVerificationCode(username, mfaMethod).subscribe({
      next: () => {
        this.logger.success('New verification code sent.');
        this.startResendCooldown();
      },
      error: (error) => {
        if (error.error.remainingSeconds) {
          this.startResendCooldown(error.error.remainingSeconds);
        } else {
          this.errors = [error.error.message || 'Error sending new code.'];
        }
      },
    });
  }

  private startResendCooldown(seconds?: number): void {
    this.resendDisabled = true;
    this.countdown = seconds || this.resendCooldownSeconds;

    const interval = setInterval(() => {
      this.countdown--;
      if (this.countdown <= 0) {
        this.resendDisabled = false;
        clearInterval(interval);
      }
    }, 1000);
  }

  private processOtp() {
    const username = localStorage.getItem('verifyUsername');
    if (username != null) {
      this.authService
        .verifyAuthenticator(username, this.verificationCode)
        .subscribe({
          next: (data: any) => {
            this.logger.success('MFA verification successful.');
            this.authService.handleJwtResponse(data);
            setTimeout(
              () =>
                (window.location.href =
                  this.simpleAuthSettings.environment.url),
              1000
            );
          },
          error: () => {
            this.errors = ['Invalid OTP verification code'];
          },
        });
    }
  }
}
